import type { Service, Project } from "@/types";

export const mockServices: Service[] = [
  {
    id: "1",
    title: "Construction",
    slug: "construction",
    description: "Pelaksanaan konstruksi gedung dan infrastruktur dengan standar presisi tinggi dan manajemen mutu terintegrasi.",
    icon: "Building2",
    status: "ACTIVE",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "2",
    title: "Engineering",
    slug: "engineering",
    description: "Solusi rekayasa teknis meliputi perencanaan struktur, sipil, dan sistem bangunan yang efisien.",
    icon: "DraftingCompass",
    status: "ACTIVE",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "3",
    title: "Project Management",
    slug: "project-management",
    description: "Pengelolaan proyek end-to-end dari perencanaan, penjadwalan, hingga serah terima dengan ketepatan waktu.",
    icon: "ClipboardList",
    status: "ACTIVE",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "4",
    title: "Maintenance",
    slug: "maintenance",
    description: "Layanan pemeliharaan preventif dan korektif untuk menjaga performa dan umur bangunan.",
    icon: "Wrench",
    status: "ACTIVE",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "5",
    title: "Consultation",
    slug: "consultation",
    description: "Konsultasi teknis dan feasibility study untuk memastikan keputusan investasi yang tepat.",
    icon: "Users",
    status: "ACTIVE",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "6",
    title: "Procurement",
    slug: "procurement",
    description: "Pengadaan material dan peralatan konstruksi berkualitas dengan jaringan supplier terpercaya.",
    icon: "Package",
    status: "ACTIVE",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const mockProjects: Project[] = [
  {
    id: "1",
    title: "Gedung Perkantoran Modern 8 Lantai",
    slug: "gedung-perkantoran-modern-8-lantai",
    category: "Construction",
    location: "[Lokasi]",
    year: "2024",
    description: "Proyek pembangunan gedung perkantoran dengan konsep modern minimalis, struktur presisi dan fasad high-performance. Meliputi pekerjaan struktur, arsitektur, dan MEP.",
    image: "/3.jpeg",
    status: "ACTIVE",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "2",
    title: "Fasilitas Industri & Warehouse",
    slug: "fasilitas-industri-warehouse",
    category: "Engineering",
    location: "[Lokasi]",
    year: "2023",
    description: "Pembangunan fasilitas industri dengan bentang lebar dan sistem utilitas terintegrasi, mengutamakan efisiensi operasional dan keamanan.",
    image: "/4.jpeg",
    status: "ACTIVE",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "3",
    title: "Renovasi Kompleks Ruko Terpadu",
    slug: "renovasi-kompleks-ruko-terpadu",
    category: "Maintenance",
    location: "[Lokasi]",
    year: "2023",
    description: "Renovasi menyeluruh kompleks ruko dengan peningkatan struktur, fasad, dan sistem drainase.",
    image: "/5.jpeg",
    status: "ACTIVE",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "4",
    title: "Gedung Pendidikan 4 Lantai",
    slug: "gedung-pendidikan-4-lantai",
    category: "Project Management",
    location: "[Lokasi]",
    year: "2024",
    description: "Manajemen konstruksi gedung pendidikan dengan pendekatan schedule presisi dan quality control berlapis.",
    image: "/6.jpeg",
    status: "ACTIVE",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "5",
    title: "Site Development & Infrastructure",
    slug: "site-development-infrastructure",
    category: "Construction",
    location: "[Lokasi]",
    year: "2022",
    description: "Pengembangan lahan dan infrastruktur penunjang kawasan industri.",
    image: "/7.jpeg",
    status: "ACTIVE",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "6",
    title: "Interior & Fit-Out Kantor Premium",
    slug: "interior-fit-out-kantor-premium",
    category: "Consultation",
    location: "[Lokasi]",
    year: "2024",
    description: "Pekerjaan interior dan fit-out dengan detail presisi, material premium dan ergonomi optimal.",
    image: "/1.jpeg",
    status: "ACTIVE",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
